name: Sync Monorepo

on:
  push:
    tags:
      - '*'

jobs:
  provide_packages_json_tagged:
    runs-on: ubuntu-20.04

    steps:
      -
        uses: actions/checkout@v2

      # required for matrix of packages set
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: none

      -   uses: "ramsey/composer-install@v1"

      - name: Install Monorepo-Builder
        run: composer require symplify/monorepo-builder:^9.0 --update-no-dev

      # get package json list
      -
        id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo_tagged:
    needs: provide_packages_json_tagged

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json_tagged.outputs.matrix)}}

    steps:
      -
        uses: actions/checkout@v2
        # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
        # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        with:
          fetch-depth: 0

      # see https://github.com/WyriHaximus/github-action-get-previous-tag
      -
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      -
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'thegreenter'
          split-repository-name: '${{ matrix.package }}'
          tag: ${{ steps.previous_tag.outputs.tag }}
          user-name: "giansalex"
          user-email: "giansalex@gmail.com"
          branch: "master"